const experiences = [
  {
    id: 1,
    startYear: "May 2024",
    endYear: "Present",
    position: "Frontend Developer",
    jobType: "Full-time",
    company: "INET Plc.",
    companyLink: "",
    desc: "Create web applications for clients of the company. Most of my works are focus on Frontend development using Vue.js by create a function for the web application and deliver good quality coding that easy for development and maintenance.",
    tech: ["Figma", "Framer", "Vue.js", "Tailwind CSS"],
    img: "https://job.science.cmu.ac.th/upload/company/1-2024-01-24-926040289.png",
  },
  {
    id: 2,
    startYear: "Nov 2023",
    endYear: "Apr 2024",
    position: "UX/UI Designer",
    jobType: "Contract",
    company: "Zenith Comp Co,. Ltd.",
    companyLink: "",
    desc: "As an entry level of UX / UI Designer, my responsibilities are to research on various things about user. For examples, the user needs, behaviors and preferences including which tool or technology is appropriate for each project and conduct them into a design which is mostly Web Design",
    tech: ["React.js", "Next.js", "TypeScript", "SCSS"],
    img: "https://www.zenithcomp.co.th/assets/images/logo.png",
  },
  {
    id: 3,
    startYear: "Jun 2023",
    endYear: "Oct 2023",
    position: "Frontend Developer",
    jobType: "Full-time",
    company: "AXONS Corporate",
    companyLink: "",
    desc: "Create web applications for organization uses. Most of my works are focus on Frontend development using Next.js by create a function for the web application to deliver good quality coding that easy to edit and maintenance.",
    tech: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    img: "https://www.axonstech.com/src/assets/img/logo.png",
  },
  {
    id: 4,
    startYear: "Nov 2022",
    endYear: "Mar 2023",
    position: "Intern Developer",
    jobType: "Internship",
    company: "Metro Systems Corporation Plc.",
    companyLink: "",
    desc: "An Internship as developer. The main responsibilities are learning new web frameworks  such as WordPress, ReactJS, NodeJS, create test case, other programming languages and other assigned works.",
    tech: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    img: "https://www.metrosystems.co.th/wp-content/uploads/2025/02/cropped-LogoMSCForWeb.png",
  },
];

export default experiences;
