import type { Metadata } from "next";
import Topbar from "./layout/Topbar";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./ThemeProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thornthan J.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialias flex justify-center items-center min-h-screen lg:scroll-smooth md:scroll-auto scroll-auto text-[#222222] bg-[#f5f5f5] dark:text-[#f5f5f5] dark:bg-[#1b1b23]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative lg:w-[97.5vw] lg:h-[95vh] md:w-full h-screen lg:rounded-xl md:rounded-none overflow-hidden lg:border dark:border-gray-500 border-gray-400">
            {/* 🔹 Top Bar */}
            <Topbar />

            {/* 🔹 Left Sidebar */}
            <aside className="absolute left-0 top-0 h-full w-14 lg:flex md:hidden hidden items-center justify-center lg:border-r dark:border-gray-500 border-gray-400 -z-0"></aside>

            {/* 🔹 Main Content Area */}
            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
