import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./ThemeProvider";
import StickySideNav from "./layout/StickySideNav";
import Loader from "./layout/Loading";
import Topbar from "./layout/Topbar";
import Footer from "./layout/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thornthan J.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased h-screen w-auto`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="theme-preference"
        >
          <Loader />
          <Topbar />
          <div className="grid lg:grid-cols-[300px_1fr] md:grid-cols-[250px_1fr] h-screen justify-between lg:gap-32 gap-12">
            <div className="pl-12">
              <StickySideNav />
            </div>

            {/* ✅ Added a wrapper for main content to ensure proper height */}
            <div className="flex flex-col h-full">
              <main className="overflow-auto relative min-h-screen flex-grow px-8 py-14">
                {children}
              </main>

              {/* ✅ Footer - Only visible on small screens */}
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
