import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./ThemeProvider";
import "./globals.css";
import StickySideNav from "./layout/StickySideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thornthan J.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased h-screen w-auto overflow-hidden text-[#222222] bg-[#f5f5f5] dark:text-[#f5f5f5] dark:bg-[#1b1b23]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid lg:grid-cols-[300px_1fr] h-screen justify-between gap-12 lg:px-12 px-4">
            <StickySideNav />

            <main className="overflow-auto h-screen px-8 py-12">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
